/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "LED3_aliases.h"
#include "LED3.h"
#include "LED2_aliases.h"
#include "LED2.h"
#include "Sensor0_aliases.h"
#include "Sensor0.h"
#include "Sensor1_aliases.h"
#include "Sensor1.h"
#include "Sensor2_aliases.h"
#include "Sensor2.h"
#include "Sensor3_aliases.h"
#include "Sensor3.h"
#include "AdcMux.h"
#include "AdcMux_SAR.h"
#include "AdcMux_IntClock.h"
#include "AdcMux_TempBuf_dma.h"
#include "AdcMux_FinalBuf_dma.h"
#include "AdcMux_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

