/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LedOn_aliases.h"
#include "LedOn.h"
#include "IR1_aliases.h"
#include "IR1.h"
#include "IR2_aliases.h"
#include "IR2.h"
#include "IR3_aliases.h"
#include "IR3.h"
#include "IR4_aliases.h"
#include "IR4.h"
#include "IR5_aliases.h"
#include "IR5.h"
#include "IR6_aliases.h"
#include "IR6.h"
#include "IR7_aliases.h"
#include "IR7.h"
#include "IR8_aliases.h"
#include "IR8.h"
#include "ADC_IR.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "LED2_aliases.h"
#include "LED2.h"
#include "LED3_aliases.h"
#include "LED3.h"
#include "LED4_aliases.h"
#include "LED4.h"
#include "LED5_aliases.h"
#include "LED5.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "SW2_aliases.h"
#include "SW2.h"
#include "MotorControl.h"
#include "Clock_1.h"
#include "LCD.h"
#include "readIRSensors.h"
#include "isrUltraSonen.h"
#include "Echo1_aliases.h"
#include "Echo1.h"
#include "Echo2_aliases.h"
#include "Echo2.h"
#include "Echo3_aliases.h"
#include "Echo3.h"
#include "TriggerReg.h"
#include "Trigger1_aliases.h"
#include "Trigger1.h"
#include "TimerUS.h"
#include "Trigger2_aliases.h"
#include "Trigger2.h"
#include "Trigger3_aliases.h"
#include "Trigger3.h"
#include "selectUS.h"
#include "statusEcho.h"
#include "ADC_IR_SAR.h"
#include "ADC_IR_IntClock.h"
#include "ADC_IR_TempBuf_dma.h"
#include "ADC_IR_FinalBuf_dma.h"
#include "ADC_IR_IRQ.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

